# Site settings
title: "Junchao Zhang"
email: ztempest0218@gmail.com
url: https://ztempest0218.github.io
description: Welcome! My name is Junchao and I am an Assistant Professor at the Institute of Statistical Mathematics in Tokyo, Japan. I graduated with a PhD in Economics from Yokohama National University in March 2017. My research interests include but not limited to labor economics and applied microeconometrics.


# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Junchao's Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
- title: twitter
  url: https://twitter.com
- title: facebook
  url: https://facebook.com
# - title: stack-overflow
#   url: http://stackoverflow.com/questions/tagged/jekyll
#- title: bitbucket
#url: http://bitbucket.org/jekyll
# - title: github
#   url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
