# Site settings
title: "Junchao Zhang"
email: ztempest0218@gmail.com
url: https://ztempest0218.github.io
description: Welcome! My name is Junchao and I am an Associate Professor at Niigata University in Japan. My research interests include but not limited to labor economics and applied microeconometrics.


# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Junchao's Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# social:
# - title: twitter
#  url: https://twitter.com
# - title: facebook
#  url: https://facebook.com
# - title: stack-overflow
#   url: http://stackoverflow.com/questions/tagged/jekyll
#- title: google
#  url: https://scholar.google.com/citations?user=5-xkIOwAAAAJ&hl=en
#- title: github
#  url: https://github.com/ztempest0218

  
# Build settings
markdown: kramdown
permalink: pretty



